### PR TITLE
Added mongoKeys hook.

### PR DESCRIPTION
**Pull request by eddyystop**
Wraps mongodb foreign keys in ObjectID

```js
const { ObjectID | = require('mongodb');
const keyFieldNames = ['_id', 'authorId', 'postId'];

{ before: {
  find: mongoKeys(ObjectID, keyFieldNames)
} };
```
```text
keys= a
from= { a: '111111111111', c: '000000000000' }
  to= { a: 313131313131313131313131, c: '000000000000' }

keys= a
from= { a: { b: '000000000000' }, c: '000000000000' }
  to= { a: { b: '000000000000' }, c: '000000000000' }

keys= a
from= { a: { '$in': [ '111111111111', '222222222222' ] },
  c: '000000000000' }
  to= { a: 
   { '$in': [ 313131313131313131313131, 323232323232323232323232 ] },
  c: '000000000000' }

keys= b
from= { b: '111111111111', c: '000000000000' }
  to= { b: 313131313131313131313131, c: '000000000000' }

keys= [ 'a', 'b' ]
from= { a: '111111111111', b: '111111111111', c: '000000000000' }
  to= { a: 313131313131313131313131,
  b: 313131313131313131313131,
  c: '000000000000' }

keys= a.x
from= { a: { x: '888888888888' } }
  to= { a: { x: 383838383838383838383838 } }

keys= [ 'b', 'a.x' ]
from= { '$or': [ { a: { x: '888888888888' } }, { b: '555555555555' } ] }
  to= { '$or': 
   [ { a: { x: 383838383838383838383838 } },
     { b: 353535353535353535353535 } ] }

keys= [ 'a', 'a.x' ]
from= { '$or': [ { a: { x: '888888888888' } }, { a: '555555555555' } ] }
  to= { '$or': 
   [ { a: { x: 383838383838383838383838 } },
     { a: 353535353535353535353535 } ] }

```

### CODE REVIEW

**Comment by eddyystop** [comment]
Published in v4.5.0

**Comment by eddyystop** [comment]
Its debateable whether _id should be included in the foreign keys list. the feathers-mongo adapter wraps _id already. On the other hand wrapping an already wrapped key should work properly.

?????

**Comment by ninique** [comment]
If you are not using MongoDB, it is throwing errors when starting the app

**Comment by eddyystop** [comment]
Dare I suggest you not use it for non-MongoDB services?

**Comment by eddyystop** [comment]
Fix published as v4.5.1. Sorry about that.

**Pull request merged**
