### PR TITLE
Correctly bind hooks and predicate functions used in conditionals.

### LINKED ISSUE #258: iff doesn't bind hook functions to service instance
when hooks are called by the iff function `this` is not bound to the service the hook was run on.

### Steps to reproduce

```
app.service('myService').hooks({
  before: {
    all: {
      function (hook) {
        console.log(this === hook.app.service('myService'));
      },
      iff(() => true, function (hook) {
        console.log(this === hook.app.service('myService'));
      }),
    }
  }
});
```

prints
```
true
false
```

### PR DESCRIPTION
**Pull request by j2L4e**
fix #258 

better late than never!

### CODE REVIEW

**Comment by eddyystop** [comment]
This is an error. However "this" does not work in other conditions hooks such as iff().else(). I've some time trying to fix them. Do you want to show your prowess?

**Comment by j2L4e** [comment]
Seems to me like it works. I'll have a closer look this weekend

**Comment by eddyystop** [comment]
There were various problems getting `this` to work the conditional hooks. I don't see the fix in `iff`, which is wrapper over `iffElse`, solving them all. So please check carefully.

From a higher level view though, people now use `context.app` and `context.service`. I don't want to encourage the use of the basically deprecated `this`, though its nice to support "legacy" hooks inside conditionals.

**Comment by j2L4e** [comment]
Closing this PR as it's not worth the needed effort. If you need to support a legacy hook inside conditionals, consider writing a wrapper hook that binds `context.service` to your legacy hook.

**Pull request closed without merging**
