### PR TITLE
close #308, add disableMultiItemCreate

### LINKED ISSUE #308: consider a new `disableMultiItemCreate` just like `disableMultiItemChange`?
just to check if Array.isArray(context.data)

### PR DESCRIPTION
**Pull request by beeplin**
Finally got some time to pick up my previous trivial ideas on #308. Just add `disableMultiItemCreate` just like `disableMultiItemChanges`.

Tests are added and passed.

### CODE REVIEW

**Comment by eddyystop** [comment]
Woot! The second hook ever contributed. Thanks.

I've added an issue to upgrade the docs https://github.com/feathers-plus/docs/issues/9

Will be in repo semver 4.2.0.

**Comment by beeplin** [comment]
:)

I just realized v4 is not on npm yet. What's the plan for publish?

**Comment by eddyystop** [comment]
When Buzzard is official released -- it isn't yet -- then v4 will be
published.

**Comment by beeplin** [comment]
lol, I have been using Buzzard for so long a time without knowing it is not released yet :PPP

**Pull request merged**
