### PR TITLE
Keep hook

### PR DESCRIPTION
**Pull request by Mattchewone**
### Summary

Created a whitelist keep hook. Rather than specifying fields you wish to remove, here you can specify fields you wish to keep.

### CODE REVIEW

**Comment by Mattchewone** [comment]
So it looks like the issue why this is failing is because on the latest version of Node `feathers-memory@1.0.1` is being installed, but on the older versions of Node `feathers-memory@1.2.1` is being installed.

In the later versions of `feathers-memory` there was a change to how the `$select` works from a custom method to using `feathers-common` select method, within that method the `id` is being added to the custom `$select`.

I have raised an issue with `feathers-memory` here - https://github.com/feathersjs-ecosystem/feathers-memory/issues/58

**Comment by eddyystop** [comment]
Thanks for creating that issue. daffl is the go-to person for that.

**Comment by eddyystop** [comment]
This looks good. I think its the very first third party hook added. Thanks.

However you have to also update the Feathers docs in feathers-docs. I'll merge both PRs together.

**Comment by Mattchewone** [comment]
Thanks @eddyystop.

I have just created a PR for the docs here - https://github.com/feathersjs/feathers-docs/pull/879

**Comment by eddyystop** [comment]
Nicely done. Thanks.

**Comment by eddyystop** [comment]
Published in 3.10.0

**Comment by bertho-zero** [comment]
`keep` is just the `pluck` hook without magic logic, no ?

**Comment by eddyystop** [comment]
Yes, like discard (no magic) vs remove (magic). The docs will be updated to highlight the feature/danger.

**Comment by bertho-zero** [comment]
All hooks with magic logic should be deprecated, no ?

**Comment by eddyystop** [comment]
We started that with the last version of Feathersjs. We're now moving into "sensitive" area where a misreading of the docs could cause data loss for server-initiated service calls.

**Pull request merged**
